import type { Metadata } from "next";
import { Langar } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import ToasterProvider from "@/provider/ToasterProvider";

const langar = Langar({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={langar.className}>
        <NextIntlClientProvider messages={messages}>
          <ToasterProvider />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
